### ISSUE TITLE
What's about 

### ISSUE THREAD

**Issue by kiquenet** [danhuss/awesome-sql#8]
Brent Ozar first-aid
https://www.brentozar.com/responder/
https://www.brentozar.com/first-aid/

More Ola Hallengren:
https://ola.hallengren.com/

The SQL Server Maintenance Solution comprises scripts for running backups, integrity checks, and index and statistics maintenance on all editions of Microsoft SQL Server 2005, SQL Server 2008, SQL Server 2008 R2, SQL Server 2012, SQL Server 2014, and SQL Server 2016

and sqlserver-kit by K.Taranov

http://sqlserver-kit.org/en
https://github.com/ktaranov/sqlserver-kit

More gurus about SQL Server
http://sqlserver-kit.org/en/home/people?perPage=100

Maybe with many gurus, tools, resources can be I get Information overload (also known as infobesity or infoxication),
https://theeconomiccontrarian.wordpress.com/2015/01/02/infoxication/

**Comment by danhuss** [comment]
Those seem good. I do want to keep the list to more applications/scripts and tools for now, so I wouldn't add the list of blogs and stuff but it looks like there's some other good stuff on that sqlserver-kit site. go ahead and open a pull request with those if you want to add them.
